environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.6"
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "5.4"
    - nodejs_version: "5.5"
    - nodejs_version: "iojs"
install:
  - "npm install -g mocha"
build: off
test_script:
  # vanilla
  - "npm run test-vanilla"
version: "{build}"